### ISSUE TITLE
Just use CDPATH environment variable

### ISSUE THREAD

**Issue by jweslley** [daltonserey/cdd#1]
- http://www.theunixschool.com/2012/04/what-is-cdpath.html
- http://jonhnnyweslley.net/br/blog/dica-linux-aumente-sua-produtividade-ao-usar-o-comando-cd/

**Comment by daltonserey** [comment]
Oi Jonhnny,

Este comando vai além do que é possível com o cdpath (até onde sei). A
ideia é poder pular diretamente pra outro diretório com apenas parte do
nome (ou um nome aproximado). Além disso, uma vez instalado, o database 
do cdd  se forma com o uso dos diretórios (por ora, só criei uma função para o `cd`).
Como eles tendem a criar vários diretórios, às vezes para as mesmas atividades,
é comum que se percam bastante. A ideia é que com o cdd possam ver todos
os diretórios com matches existentes facilmente.

[]s
Dalton
